version: "3.9"

services:
  client:
    build: ./client
    depends_on:
    - server

  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - "logsdb:/app/data"
    
volumes:
  logsdb:
